markfairbanks/tidypolars

poetry.lock, pyproject.toml, tests/test_tidyframe.py, tidypolars/tidypolars.py
=> Remove numpy dependency

CHANGELOG.md, tests/test_tidypolars.py, tidypolars/tidypolars.py
=> Add cbind rbind

CHANGELOG.md, pyproject.toml, tests/test_tidypolars.py, tidypolars/tidypolars.py
=> Implement `.pull()`

CHANGELOG.md, tests/test_groupby.py, tests/test_tidypolars.py, tidypolars/tidypolars.py
=> Implement `.slice()`

tests/test_tidypolars.py, tidypolars/tidypolars.py
=> Implement rename

CHANGELOG.md, tests/test_groupby.py, tests/test_tidypolars.py, tidypolars/tidypolars.py
=> Implement head and tail methods

tidypolars/__init__.py, tidypolars/docstrings_Tibble.py, tidypolars/funs.py, tidypolars/tidypolars.py
=> Move docstrings to separate module

README.md, docs/example.ipynb, poetry.lock, pyproject.toml, tests/test_tidypolars.py, tidypolars/tidypolars.py
=> Implement to/from polars/pandas

tests/test_tidypolars.py, tidypolars/tidypolars.py
=> Simplify Tibble construction

CHANGELOG.md, tidypolars/funs.py, tidypolars/tidypolars.py
=> Read/write csv/parquet

tests/test_tidypolars.py, tidypolars/tidypolars.py
=> Relocate cols to beginning by default

CHANGELOG.md, tests/test_tidypolars.py, tidypolars/tidypolars.py
Closes #76 
Take a look at the ToDo and let me know if you have any recommendations.
=> Add count()

tidypolars/tidypolars.py
=> Create Tibble docstring

CHANGELOG.md, README.md, docs/example.ipynb, tests/test_funs.py, tidypolars/funs.py, tidypolars/tidypolars.py, tidypolars/utils.py
See #90 
Functions implemented:
* `abs`
* `first`
* `last`
=> More functions

CHANGELOG.md, tests/test_stringr.py, tidypolars/stringr.py
=> Add `str_extract()` to `stringr` module

tidypolars/tidypolars.py
=> Update docs to examples of expression functions

CHANGELOG.md, docs/reference.md, pyproject.toml, tests/test_tidypolars.py, tidypolars/tidypolars.py
=> Implement `.set_names()`

CHANGELOG.md, docs/conf.py, docs/reference.md, tests/test_funs.py, tests/test_tidypolars.py, tidypolars/funs.py, tidypolars/stringr.py, tidypolars/tidypolars.py
=> Implement `replace_null`

tidypolars/tidypolars.py
=> Allows tidyselect to work with relocate

CHANGELOG.md, docs/reference.md, tests/test_stringr.py, tidypolars/stringr.py
=> Implement `paste`/`paste0`

docs/autoapi/index.rst, docs/autoapi/tidypolars/funs/index.rst, docs/autoapi/tidypolars/index.rst, docs/autoapi/tidypolars/lubridate/index.rst, docs/autoapi/tidypolars/reexports/index.rst, docs/autoapi/tidypolars/stringr/index.rst, docs/autoapi/tidypolars/tidypolars/index.rst, docs/autoapi/tidypolars/tidyselect/index.rst, pyproject.toml, tidypolars/tidypolars.py
=> Fix html printing

CHANGELOG.md, tests/test_tidypolars.py, tidypolars/tidypolars.py
=> Use diagonal concat in `.bind_rows()`

CHANGELOG.md, tests/test_lubridate.py, tidypolars/lubridate.py
=> Pass `fmt` arg in `as_date`/`as_datetime`

CHANGELOG.md, docs/reference.md, tests/test_funs.py, tidypolars/funs.py, tidypolars/tibble.py
=> Implement `row_number()`

CHANGELOG.md, docs/reference.md, tests/test_funs.py, tests/test_tibble.py, tidypolars/tibble.py
=> Implement `.separate()`

CHANGELOG.md, tests/test_stringr.py, tidypolars/stringr.py
=> Implement str_c/_ends/_starts

CHANGELOG.md, tests/test_funs.py, tidypolars/funs.py
=> Implement `coalesce()`

CHANGELOG.md, docs/reference.md, tests/test_funs.py, tidypolars/funs.py
=> Implement `as_boolean()`

docs/reference.md, poetry.lock, pyproject.toml, tests/test_tibble.py, tidypolars/tibble.py
=> Implement `.unite()`

CHANGELOG.md, docs/reference.md, poetry.lock, tests/test_funs.py, tidypolars/funs.py, tidypolars/utils.py
=> Add cor, cov, log, log10, rep, var

poetry.lock, pyproject.toml, tidypolars/tibble.py
=> Polars v0.14.0 compatibility

tests/test_funs.py, tests/test_groupby.py, tests/test_tibble.py, tidypolars/tibble.py
=> Convert `by` to `_by`

tests/test_tidyselect.py, tidypolars/tidyselect.py, tidypolars/utils.py
=> Convert tidyselect helpers to use polars selectors

CHANGELOG.md, tests/test_funs.py, tests/test_groupby.py, tests/test_lubridate.py, tests/test_stringr.py, tests/test_tibble.py, tests/test_tidyselect.py, tidypolars/__init__.py, tidypolars/funs.py, tidypolars/lubridate.py, tidypolars/tibble_df.py, tidypolars/tidyselect.py
=> Convert `Tibble`class to `tibble`

CHANGELOG.md, tests/test_tibble.py, tidypolars/tibble_df.py
=> Add `__getitem__`

docs/reference.md
=> Docs cleanup

poetry.lock, tests/test_tibble.py, tidypolars/tibble_df.py
=> Add underscores to `.relocate()` args

tests/test_tibble.py, tidypolars/tibble_df.py
=> Clean up `.rename()`

README.md
=> Update readme for v0.3.0

tidypolars/tibble_df.py
=> Fix `.as_pandas()`

CHANGELOG.md, tests/test_funs.py, tidypolars/funs.py, tidypolars/utils.py
=> Refactor `case_when()`

CHANGELOG.md, tidypolars/tibble_df.py
=> Add `.print()`

CHANGELOG.md, tidypolars/tibble_df.py
=> Rename `mapping` to `_mapping` in `.rename()`

CHANGELOG.md, tidypolars/tibble_df.py
=> Add `.plot`

tidypolars/funs.py
=> Correct functions in examples

CHANGELOG.md, docs/reference.md, tidypolars/tibble_df.py
=> Add `.glimpse()`
